version: '3.9'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - /Users/huynguyen/Data/database-data/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: bio-ecommerce
      POSTGRES_PASSWORD: mysecretpassword

  backend:
    build: .
    restart: always
    ports:
      - 1337:1337
      - 9229:9229
    volumes: 
      # - ./:/./app
      - /node_modules
    environment:
      - DATABASE_PORT=5432
      - DATABASE_NAME=bio-ecommerce
      - DATABASE_USERNAME=postgres
      - DATABASE_HOST=db
    depends_on:
      - db
