import Head from 'next/head';
import { useQuery } from 'urql';
import Skeleton from 'react-loading-skeleton';
import { PRODUCT_QUERY } from '../lib/query';
import Product from '../components/Product';
import { Gallery } from '../styles/Gallery';
import 'react-loading-skeleton/dist/skeleton.css';
import axios from 'axios';

export default function Home() {
  const [results] = useQuery({ query: PRODUCT_QUERY });
  const { data, fetching, error } = results;

  if (fetching) return <p>Loading...</p>;
  if (error) {
    return (
      <p>
        Oh no... {error.message}
      </p>
    );
  }
  const products = data.products.data;

  if (!products.length) {
    return <h1>No products</h1>;
  }

  return (
    <div>
      <Head>
        <title>Styled Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Gallery>
          {/* <Skeleton /> */}
          {products.map(product => (
            <Product key={product.attributes.slug} product={product} />
          ))}
        </Gallery>
      </main>
    </div>
  );
}

export async function getServerSideProps() {
  const result = await axios.get(`http://192.168.20.230:1337/api/products`);
  const products = result.data.data;
  return { props: { products } };
}
